substitutions:
  rooms_amount: "3"

  # Room icons
  room_icon_1:                    "\U000F04A6"  # mdi:silverware-variant (Virtuvė)
  room_icon_2:                    "\U000F04B9"  # mdi:sofa (Svetainė)
  room_icon_3:                    "\U000F032F"  # mdi:laptop (Darbo kambarys)
  room_icon_4:                    "\U000F032F"  # unused

  # Light icons
  track_light_icon:               "\U000F0914" # mdi:track-light
  ceiling_light_multiple_icon:    "\U000F18DD" # mdi:ceiling-light-multiple
  flor_lamp_icon:                 "\U000F08DD" # mdi:floor-lamp
  vanity_light_icon:              "\U000F11E1" # mdi:vanity-light

packages:
  room_selector: !include room_select.yaml

  virtuve: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_1"
      room_icon: "${room_icon_1}"
      lights_amount: "7"

      light_entity_1: "light.virtuve_pirmas_switch_1"   # Sviestuvas
      light_entity_2: "light.virtuve_pirmas_switch_2"   # Baras
      light_entity_3: "light.virtuves_antras_switch_1"  # Led Virsus
      light_entity_4: "light.virtuves_antras_switch_2"  # Led Apacia
      light_entity_5: "light.virtuve_trecias_switch_1"  # Viryklė
      light_entity_6: "light.virtuve_trecias_switch_2"  # Trecias 2
      light_entity_7: "light.wled_virtuve"              # WLED-virtuve

      light_icon_1: "${ceiling_light_multiple_icon}"
      light_icon_2: "${track_light_icon}"
      light_icon_3: "${track_light_icon}"
      light_icon_4: "${flor_lamp_icon}"
      light_icon_5: "${ceiling_light_multiple_icon}"
      light_icon_6: "${track_light_icon}"
      light_icon_7: "${vanity_light_icon}"

  svetaine: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_2"
      room_icon: "${room_icon_2}"
      lights_amount: "2"

      light_entity_1: "light.shellydimmer2svetaine"           # dimmer
      light_entity_2: "switch.plus1pmlivingroom_switch_0"     # switch (Sviestuvas)
      light_entity_3: "light.shellydimmer2svetaine"           # unused
      light_entity_4: "light.shellydimmer2svetaine"           # unused
      light_entity_5: "light.shellydimmer2svetaine"           # unused
      light_entity_6: "light.shellydimmer2svetaine"           # unused
      light_entity_7: "light.shellydimmer2svetaine"           # unused

      light_icon_1: "${ceiling_light_multiple_icon}"
      light_icon_2: "${ceiling_light_multiple_icon}"
      light_icon_3: "${ceiling_light_multiple_icon}"
      light_icon_4: "${ceiling_light_multiple_icon}"
      light_icon_5: "${ceiling_light_multiple_icon}"
      light_icon_6: "${ceiling_light_multiple_icon}"
      light_icon_7: "${ceiling_light_multiple_icon}"

  darbo_kambarys: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_3"
      room_icon: "${room_icon_3}"
      lights_amount: "2"

      light_entity_1: "light.leds"                      # M5-Darbo-Kambarys LEDs
      light_entity_2: "light.philips_light_sread1"      # Vaiku Staline Lempa
      light_entity_3: "light.leds"                      # unused
      light_entity_4: "light.leds"                      # unused
      light_entity_5: "light.leds"                      # unused
      light_entity_6: "light.leds"                      # unused
      light_entity_7: "light.leds"                      # unused

      light_icon_1: "${track_light_icon}"
      light_icon_2: "${flor_lamp_icon}"
      light_icon_3: "${track_light_icon}"
      light_icon_4: "${track_light_icon}"
      light_icon_5: "${track_light_icon}"
      light_icon_6: "${track_light_icon}"
      light_icon_7: "${track_light_icon}"

  room4_placeholder: !include
    file: rooms.yaml
    vars:
      room_name: "room_name_4"
      room_icon: "${room_icon_4}"
      lights_amount: "1"

      light_entity_1: "light.leds"
      light_entity_2: "light.leds"
      light_entity_3: "light.leds"
      light_entity_4: "light.leds"
      light_entity_5: "light.leds"
      light_entity_6: "light.leds"
      light_entity_7: "light.leds"

      light_icon_1: "${track_light_icon}"
      light_icon_2: "${track_light_icon}"
      light_icon_3: "${track_light_icon}"
      light_icon_4: "${track_light_icon}"
      light_icon_5: "${track_light_icon}"
      light_icon_6: "${track_light_icon}"
      light_icon_7: "${track_light_icon}"
